---
# Which node can reach which VLAN, and over which bridge.
#
# A node appears under a VLAN only if it is physically cabled to it.
# Adding a node to a VLAN here makes it eligible for placement

nodes:
  - name: guava
    template_vm_id: 9001
    vlans:
      sboai: vmbr424
      netsoft: vmbr427

  - name: framboise
    template_vm_id: 9000
    vlans:
      sboai: vmbr0

  - name: eiffel
    vlans:
      sboai: vmbr0

  - name: magenta
    vlans:
      sboai: vmbr0

  - name: bougainvillier
    vlans:
      sboai: vmbr0

  - name: cherry
    vlans:
      sboai: vmbr0

  - name: blida
    vlans:
      sboai: vmbr0

  - name: jasmin
    vlans:
      sboai: vmbr0
